import { z } from "zod/v4";

import {
  booleanInt,
  currencyCode,
  dateTimeString,
  decimalAmount,
  integerString,
  optionalString,
  requiredString,
} from "./primitives";

export const transactionBaseSchema = z.object({
  status: requiredString("status", 30),
  tran_date: dateTimeString,
  tran_id: requiredString("tran_id", 30),
  val_id: requiredString("val_id", 50),
  amount: decimalAmount,
  store_amount: decimalAmount,
  card_type: requiredString("card_type", 50),
  card_no: optionalString(80),
  currency: currencyCode,
  bank_tran_id: optionalString(80),
  card_issuer: optionalString(100),
  card_brand: optionalString(30),
  card_issuer_country: optionalString(50),
  card_issuer_country_code: optionalString(2),
  currency_type: currencyCode.optional(),
  currency_amount: decimalAmount.optional(),
  emi_instalment: integerString.optional(),
  emi_amount: decimalAmount.optional(),
  discount_amount: decimalAmount.optional(),
  discount_percentage: decimalAmount.optional(),
  discount_remarks: optionalString(255),
  value_a: optionalString(255),
  value_b: optionalString(255),
  value_c: optionalString(255),
  value_d: optionalString(255),
  risk_level: booleanInt.optional(),
  risk_title: optionalString(50),
  currency_rate: optionalString(),
  base_fair: optionalString(),
  validated_on: dateTimeString.optional(),
  gw_version: optionalString(),
  emi_description: optionalString(),
  emi_issuer: optionalString(),
  account_details: optionalString(),
});

export type TransactionBase = z.infer<typeof transactionBaseSchema>;
